FROM node:14-alpine

USER root
WORKDIR /home/node/slides-frontend

RUN apk add git && npm i -g local-web-server

COPY build .

EXPOSE 8080

USER 1001
# CMD npx ws -p 8080 --spa index.html // call the correct cmd to start frontend
